apiVersion: batch/v1
kind: Job
metadata:
  name: weaver-job-ik-QCD
  labels:
    app: hwwtagger
spec:
  template:
    spec:
      containers:
      - name: container
        image: gitlab-registry.nrp-nautilus.io/raghsthebest/hww-tagger/weaver
        command:
        - "/bin/bash"
        - "-c"
        - >
          git clone https://github.com/cmantill/weaver && cd weaver && 
          (python -u train.py
          --data-train '/hwwtaggervol/training/ak15_Jul27/train/QCD*/*.root' 
          --data-config data/ak15_points_pf_sv_mass_regression_QCD.yaml
          --network-config networks/particle_net_pf_sv_mass_regression.py
          --model-prefix /hwwtaggervol/models/v04_regression/4_ak15Jul27_v04_QCD_bsize128_fstep0p02_lr3em3 
          --num-workers 3 
          --batch-size 128 
          --start-lr 3e-3 
          --num-epochs 20 
          --optimizer ranger 
          --gpu 0,1,2
          --fetch-step 0.02
          --regression-mode
          | tee /hwwtaggervol/logs/regression_4_ak15_v04_QCD_bsize128_fstep0p02_lr3em3_4q.log &
          wait)
        volumeMounts:
        - mountPath: /hwwtaggervol
          name: hwwtaggervol
        resources:
          limits:
            memory: 256Gi
            cpu: "4"
            nvidia.com/gpu: "3"
          requests:
            memory: 70Gi
            cpu: "3"
            nvidia.com/gpu: "3"
      volumes:
      - name: hwwtaggervol
        persistentVolumeClaim:
          claimName: hwwtaggervol
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - us-west
              - key: gpu-type
                operator: In
                values:
                - "1080"
                - 1080Ti
                - 2080Ti
      restartPolicy: Never
  backoffLimit: 0


